### ISSUE TITLE
Format of input csv

### ISSUE THREAD

**Issue by calvinmccarter** [SimonKitSangChu/EsmTherm#2]
Can you please provide information about the expected format of the input csv for `evaluate.py` -- perhaps an example input file? In particular, I am unsure how you evaluate multiple-point mutations as mentioned in the abstract. Thanks!

**Comment by SimonKitSangChu** [comment]
Sure. I have added an example input as `examples/evaluate_input.csv`. Note that only column sequence is needed. The output csv will have a new column "prediction".

Since the model attempts to predict the folding stability (dG) instead of its change upon mutation (ddG), we simply subtracted the difference of predictions from two sequences for any "mutation" including multiple-point mutations.
